using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace IqraGenerators
{
    [Generator]
    public class FlowAppSchemaGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Find all partial classes implementing IFlowAction
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => IsCandidateClass(s),
                    transform: (ctx, _) => GetClassSemanticTarget(ctx))
                .Where(m => m != null);

            // 2. Combine with Additional Files (The JSON files)
            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());
            var jsonFiles = context.AdditionalTextsProvider.Where(file => file.Path.EndsWith(".json"));

            var provider = compilationAndClasses.Combine(jsonFiles.Collect());

            // 3. Execute generation
            context.RegisterSourceOutput(provider, (spc, source) => Execute(spc, source.Left.Left, source.Left.Right, source.Right));
        }

        private static bool IsCandidateClass(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax c && c.BaseList != null;
        }

        private static ClassDeclarationSyntax? GetClassSemanticTarget(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;

            // Check if it implements IFlowAction
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            if (symbol == null) return null;

            if (symbol.AllInterfaces.Any(i => i.Name == "IFlowAction"))
            {
                return classDeclaration;
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> classes, ImmutableArray<AdditionalText> jsonFiles)
        {
            foreach (var classDecl in classes)
            {
                if (classDecl == null) continue;

                var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
                var classSymbol = semanticModel.GetDeclaredSymbol(classDecl);
                if (classSymbol == null) continue;

                // Convention: If class is "BookMeetingAction", look for "BookMeeting.json"
                // logic: remove "Action" from end if present
                var className = classSymbol.Name;
                var baseName = className.EndsWith("Action")
                    ? className.Substring(0, className.Length - 6)
                    : className;

                // Find the JSON file in the same directory
                var sourceFilePath = classDecl.SyntaxTree.FilePath;
                var sourceDirectory = Path.GetDirectoryName(sourceFilePath);

                var jsonFile = jsonFiles.FirstOrDefault(f =>
                {
                    var jsonDir = Path.GetDirectoryName(f.Path);
                    var jsonName = Path.GetFileNameWithoutExtension(f.Path);

                    // Match directory AND match name (BookMeeting.json)
                    return jsonDir == sourceDirectory && jsonName == baseName;
                });

                if (jsonFile == null)
                {
                    throw new Exception($"JSON file '{baseName}.json' not found in the same directory as '{sourceFilePath}'");
                }

                var jsonContent = jsonFile.GetText()?.ToString();
                if (string.IsNullOrEmpty(jsonContent)) throw new Exception($"JSON file '{baseName}.json' is empty");

                var jsonData = JsonSerializer.Deserialize<JsonDocument>(jsonContent!);
                if (jsonData == null) throw new Exception($"JSON file '{baseName}.json' is not valid JSON");

                var minifiedJson = JsonSerializer.Serialize(jsonData, new JsonSerializerOptions { WriteIndented = false });

                // Escape double quotes for C# string literal
                // Or use Raw String Literals (requires C# 11, .NET 7+)
                var generatedCode = $$""""
                // <auto-generated/>
                using System;
                using System.Text.RegularExpressions;

                namespace {{classSymbol.ContainingNamespace}}
                {
                    public partial class {{className}}
                    {
                        public string GetInputSchemaJson()
                        {
                            return Regex.Unescape("""{{Regex.Escape(minifiedJson)}}""");
                        }
                    }
                }
                """";

                context.AddSource($"{className}.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            }
        }
    }
}